approvals:
  # PR needs at least 4 approvals
  minimum: 1
  # approval = comment that matches this regex
  pattern: "^\\s*(:?\\+1:?|👍)\\s*$"
  from:
    # commenter must be either one of:
    # a public zalando org member
    orgs:
      - zalando
    # a collaborator of the repo
    collaborators: true
