#!/bin/bash

touch /var/run/haproxy.pid

cat <<- EOF > /etc/confd/conf.d/haproxy.toml
[template]
prefix = "${HAPROXY_KEY}/${CLUSTER}"
keys = [
  "services"
]

owner = "haproxy"
mode = "0644"
src = "haproxy.tmpl"
dest = "/etc/haproxy/haproxy.cfg"

check_cmd = "/usr/sbin/haproxy -c -f {{ .src }}"
reload_cmd = "haproxy -f /etc/haproxy/haproxy.cfg -p /var/run/haproxy.pid -D -sf $(cat /var/run/haproxy.pid)"
EOF
