apiVersion: v1
kind: Service
metadata:
  name: patroni-service
spec:
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
    name: pgsql-master
  - port: 5001
    targetPort: 5001
    protocol: TCP
    name: pgsql-slave
  - port: 8001
    targetPort: 8001
    protocol: TCP
    name: patroni-api
  selector:
    app: patroni
