---
apiVersion: v1
kind: ReplicationController
metadata:
  name: patroni-controller
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: patroni
    spec:
      containers:
      - name: patroni
        image: 192.168.64.1:5000/patroni
        args:
          - --etcd=192.168.64.6
        env:
          - name: ADMINUSER
            value: "postgres"
          - name: ADMINPASS
            value: "dbadmin"
        ports:
          - containerPort: 5000
          - containerPort: 5001
          - containerPort: 8001
        livenessProbe:
          tcpSocket:
            port: 5432
          initialDelaySeconds: 15
          timeoutSeconds: 1
        volumeMounts:
          - mountPath: /srv/data
            name: data
      volumes:
        - hostPath:
            path: /data
          name: data
